#!/bin/bash

if [ -d "src" ]; then
    cd "src"
fi

tmp="$(find -name "$1" -type f)"

if [ "$tmp" == "" ]; then
	echo "file $1 not found"
	xdotool key Up
	exit
fi

for file in $tmp
do
	results="$results $file"
done

nvim $results
