#!/bin/bash

# bash completion
if [ "$1" == "-c" ]; then
	complete -W "$(op_completer.py)" op
	return
fi

if [ -d "src" ]; then
    cd "src"
fi

if [ "$1" == "-p" ]; then
	tmp="$(grep -rlI "$2")"
	pattern="$2"
else
	tmp="$(find -name "$1" -type f)"
fi


if [ "$tmp" == "" ]; then
	if [ -n "$pattern" ]; then
		echo "pattern $pattern not found"
	else
		echo "file $1 not found"
	fi
	xdotool key Up
	exit 1
fi

for file in $tmp
do
	results="$results $file"
done

if [ -n "$pattern" ]; then
	nvim -c ":0; /$pattern" $results
else
	nvim $results
fi
